import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import ThemeProviders from "@/app/ThemeProviders";
import SectionContainer from "@/components/SectionContainer";
import Header from "@/components/Header";
// import {ThemeProvider} from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <ThemeProviders>
                <SectionContainer>
                    <Header />
                    {children}
                </SectionContainer>
            </ThemeProviders>
            </body>
        </html>
    );
}
